name: Portfolio 
on:
  push:
    branches:
    - main 
  jobs:
   deploy:
   runs-on: ubuntu-latest
   step:
   - name: Checkout
   uses: action/checkout@v1

   - name: Configure AWS Credentials
     uses: aws-actions/configure-aws-creadentials 
     with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     aws-region:us-east-1

     - nmae: Deploy static to S3 bucket
       run: aws s3 sync . s3://mushtaq-portfilio 
     
   
